# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[directory]
truncate_to_repo = false
truncation_length = 2

[git_branch]
format = "[$branch]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"
modified = "*"
style = "red"

[nodejs]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[ruby]
disabled = true
