#!/bin/bash

cd "$(dirname "$0")/.."

set -e

link() {
  if ! [ -L "$2" ]
  then
    ln -sfv "$DOTFILES/$1" "$2"
  else
    rm -rv "$2"
    ln -sv "$DOTFILES/$1" "$2"
  fi
}

# Link up .dotfiles
for DOTFILE in .*;
do
  HOMEFILE="$HOME/$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"

  # Skip certain files
  echo $DOTFILE | egrep -q '(^\.git/$|^\.gitignore$|^\.vscode/$|\.\.?/$)' && continue

	link $DOTFILE $HOMEFILE
done

# Linking up vscode
VSCODE="$HOME/Library/Application Support/Code/User" && mkdir -p "$VSCODE"

link ".vscode/snippets/" "$VSCODE"
link ".vscode/settings.json" "$VSCODE/settings.json"

# install npm packages
npm install

# Install vscode extensions
while read extension; do
  code --install-extension "$extension"
done <$DOTFILES/.vscode/extensions
